### ISSUE TITLE
Consider using a proper license

### ISSUE THREAD

**Issue by Kijewski** [Blobfolio/utc2k#2]
E.g. [Zero-Clause BSD](https://opensource.org/licenses/0BSD) or [MIT No Attribution](https://opensource.org/licenses/MIT-0) if you want the license to be as free as possible.

WTFPL is not usable in countries that don't have a concept of public domain dedication, like all of continental Europe.

Even in for the US the license seems questionable. "[C]hanging it is allowed as long as the name is changed" – So, if Alice modifies your code and releases it under a new name; and Bob modifies and distributes Alice's code under your name, did Bob infringe your rights? What if Alice modifies and distributes your code twice? Can she use the original name again?

**Comment by joshstoik1** [comment]
Hi @Kijewski!

Thanks for reaching out! I'm sorry to hear Europe doesn't recognize the Public Domain. That must make things difficult.

MIT-0 is a good approximation for the WTFPL, but it is written in legalese, which makes me uncomfortable because such language is exclusionary and carries an implicit threat of judicial violence (especially here in the US). The WTFPL is more of a protest against the very concept of software licensing (rather than an actual, enforceable license), which makes me feel better.

But just in case it wasn't clear, I have _no rights_ in regards to this software that you could possibly infringe upon. Go wild! If you aren't able to use this library directly, just steal it and slap an MIT-0 license on the fork. :wink: 

It is, however, worth noting that the optional crate features _do_ have third-party dependencies that _are_ subject to the licensing restrictions set by their authors. The `serde` feature brings in [serde](https://crates.io/crates/serde), while the `local` feature brings in [tz-rs](https://crates.io/crates/tz-rs) and [const_fn](https://crates.io/crates/const_fn/0.4.9). All three of those dependencies are dual-licensed MIT/Apache 2.0, which should make reconciling them within a Rust app pretty easy.

I do really appreciate you reaching out, though, and don't want you to feel discouraged by my philosophical hardline. If you have any other ideas for making this library better, please feel free to open another issue.

Thanks again!
